#!/usr/bin/env python3

import RPi.GPIO as GPIO
import time
import subprocess

TRIG = 11       # GPIO pin for ultrasonic sensor's TRIG
ECHO = 12       # GPIO pin for ultrasonic sensor's ECHO
BUZZER = 13     # GPIO pin for active buzzer
IR_SENSOR = 18  # GPIO pin for infrared motion sensor

def setup():
    GPIO.setmode(GPIO.BOARD)
    GPIO.setwarnings(False)
    GPIO.setup(TRIG, GPIO.OUT)
    GPIO.setup(ECHO, GPIO.IN)
    GPIO.setup(BUZZER, GPIO.OUT)
    GPIO.setup(IR_SENSOR, GPIO.IN)

def distance():
    GPIO.output(TRIG, 0)
    time.sleep(0.000002)

    GPIO.output(TRIG, 1)
    time.sleep(0.00001)
    GPIO.output(TRIG, 0)

    while GPIO.input(ECHO) == 0:
        pass
    time1 = time.time()
    while GPIO.input(ECHO) == 1:
        pass
    time2 = time.time()

    during = time2 - time1
    return during * 340 / 2 * 39.37  # Convert to inches

def controlBuzzer(state):
    GPIO.output(BUZZER, state)

def waitForMotion(timeout=10):
    start_time = time.time()
    while True:
        i = GPIO.input(IR_SENSOR)
        if i == 1 or time.time() - start_time > timeout:
            break

def waitForNoMotion(timeout=10):
    start_time = time.time()
    while True:
        i = GPIO.input(IR_SENSOR)
        if i == 0 or time.time() - start_time > timeout:
            break

def textToSpeech(message):
    subprocess.run(['espeak', message])

def loop():
    try:
        while True:
            waitForMotion()
            dis = distance()
            print(f'Distance: {dis:.2f} inches')

            if dis <= 30:
                controlBuzzer(GPIO.LOW)
                textToSpeech("HUMAN AHEAD!!")
            else:
                controlBuzzer(GPIO.HIGH)

            waitForNoMotion()
            time.sleep(0.1)

    except KeyboardInterrupt:
        destroy()

def destroy():
    GPIO.cleanup()

if __name__ == "__main__":
    setup()
    try:
        loop()
    except KeyboardInterrupt:
        destroy()
