#!/usr/bin/env python3

import subprocess
import RPi.GPIO as GPIO
import time

# Rest of the code remains the same

def loop():
    try:
        while True:
            waitForMotion()
            dis = distance()
            print(f'Distance: {dis:.2f} inches')
            if dis <= 30:
                GPIO.output(BUZZER, GPIO.LOW)
                # Convert text to speech
                speech = "HUMAN AHEAD !!"
                subprocess.call(['espeak', speech])
            else:
                GPIO.output(BUZZER, GPIO.HIGH)
            waitForNoMotion()
    except KeyboardInterrupt:
        destroy()
