#!/usr/bin/env python3

import RPi.GPIO as GPIO
import time

TRIG = 11
ECHO = 12
BUZZER = 13  # GPIO pin for the buzzer

def setup():
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(TRIG, GPIO.OUT)
    GPIO.setup(ECHO, GPIO.IN)
    GPIO.setup(BUZZER, GPIO.OUT)  # Set the buzzer pin as an output

def distance():
    GPIO.output(TRIG, 0)
    time.sleep(0.000002)

    GPIO.output(TRIG, 1)
    time.sleep(0.00001)
    GPIO.output(TRIG, 0)

    while GPIO.input(ECHO) == 0:
        a = 0
    time1 = time.time()
    while GPIO.input(ECHO) == 1:
        a = 1
    time2 = time.time()

    during = time2 - time1
    return during * 340 / 2 * 100

def buzz():
    GPIO.output(BUZZER, GPIO.HIGH)
    time.sleep(0.1)  # Adjust this time to control the buzzer sound duration
    GPIO.output(BUZZER, GPIO.LOW)

def loop():
    min_distance = 30  # Set the minimum distance for the buzzer to sound (in centimeters)

    while True:
        dis = distance()
        print(dis, 'cm')
        
        if dis < min_distance:
            print("Object is too close!")
            buzz()  # Sound the buzzer
        time.sleep(0.3)

def destroy():
    GPIO.cleanup()

if __name__ == "__main__":
    setup()
    try:
        loop()
    except KeyboardInterrupt:
        destroy()
